name: Build and deploy Node.js app to Azure Web App - stroopy-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install and build backend
        run: |
          cd backend
          npm ci
          npm run build

      # ✅ Upload only what Azure needs to run
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            backend/dist
            backend/package.json
            backend/package-lock.json

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_672C9EBE5AAB443AA11A781856D0E372 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6317D4C68975432E900A56B20FFD31B1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1541510E507C4F1297F64BF92F5CBCA7 }}

      # ✅ Deploy compiled code, not TypeScript source
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'stroopy-backend'
          slot-name: 'Production'
          package: backend/dist
